export const BUILTIN_FLASHCARDS = [
  {
    id: 'builtin-methods-of-research',
    title: 'Research Basics',
    subject: 'Methods of Research',
    description: 'Fundamental research concepts and terminology.',
    cards: [
      ['What is research?', 'A systematic investigation to establish facts or principles'],
      ['Qualitative research', 'Research that focuses on understanding phenomena through observation and interviews'],
      ['Quantitative research', 'Research that uses numerical data and statistical analysis'],
      ['Experimental research', 'Research involving experiments to test hypotheses'],
      ['Survey research', 'Research using questionnaires to collect data from a population'],
      ['Case study', 'In-depth study of a particular instance or event'],
      ['Research ethics', 'Guidelines for conducting research responsibly and ethically'],
      ['Hypothesis', 'A testable statement predicting the outcome of research'],
      ['Literature review', 'A summary and evaluation of existing research on a topic'],
      ['Sampling', 'Process of selecting a representative group from a population for study'],
      ['Variables', 'Elements or factors that can change or be measured in research'],
      ['Independent variable', 'The factor that is manipulated to observe its effect'],
      ['Dependent variable', 'The factor that is measured to see the effect of changes'],
      ['Control group', 'Group in an experiment not exposed to the independent variable'],
      ['Random sampling', 'Selecting participants randomly to avoid bias'],
      ['Reliability', 'The consistency of a research measurement over time'],
      ['Validity', 'The accuracy of a measurement in reflecting what it is supposed to measure'],
      ['Data analysis', 'The process of organizing and interpreting collected data'],
      ['Research design', 'The overall strategy used to integrate the different components of a study'],
      ['Primary data', 'Data collected directly from first-hand sources'],
      ['Secondary data', 'Data collected from existing sources or research']
    ]
  },

  {
    id: 'builtin-engineering-management',
    title: 'Eng Management',
    subject: 'Engineering Management',
    description: 'Engineering management concepts covering planning, leadership, organizing, and controlling.',
    cards: [
      ['LESSON 5: What is the purpose of planning in engineering management?', 'Planning is the process of setting goals, defining strategies, and establishing action plans to achieve organizational objectives efficiently'],
      ['What are the key types of plans in engineering management?', 'Strategic plans (long-term direction), tactical plans (intermediate goals), and operational plans (day-to-day activities)'],
      ['What is the planning hierarchy?', 'Objectives → Strategies → Policies → Procedures → Rules; flows from highest to lowest level'],
      ['Define forecasting in planning context', 'Predicting future conditions and trends based on historical data and market analysis to inform decisions'],
      ['What are constraints on planning?', 'Internal constraints (resources, capabilities) and external constraints (market conditions, regulations, competition)'],
      ['What is a project scope statement?', 'A document that clearly defines project objectives, deliverables, boundaries, and success criteria'],
      ['Explain SMART goals in planning', 'Specific, Measurable, Achievable, Relevant, Time-bound objectives that provide clear direction'],
      ['What is risk planning in projects?', 'Identifying potential risks early and developing mitigation strategies to minimize negative impacts'],
      ['Define budget planning in engineering projects', 'Estimating and allocating financial resources needed for project activities and contingencies'],
      ['What is timeline or schedule planning?', 'Determining the sequence and duration of project activities to complete deliverables on time'],

      ['LESSON 6: What is leadership in engineering management?', 'Leadership is guiding, motivating, and influencing team members to achieve organizational goals effectively'],
      ['What are the key leadership styles?', 'Autocratic (directive), Democratic (participative), Laissez-faire (delegative), and Transformational leadership'],
      ['What is transformational leadership?', 'Leadership that inspires followers to exceed expectations and embrace organizational vision and values'],
      ['What is motivation in leadership?', 'Process of stimulating individuals to take actions that accomplish goals and fulfill needs'],
      ["Explain Maslow's Hierarchy of Needs", 'Five levels of human needs from basic (physiological) to highest (self-actualization) that drive motivation'],
      ['What is emotional intelligence in leadership?', 'Ability to recognize, understand, and manage emotions in oneself and others for effective leadership'],
      ['Define delegation in leadership', 'Assigning responsibility and authority to capable team members to accomplish specific tasks'],
      ['What makes an effective leader in engineering?', 'Technical knowledge, clear communication, problem-solving skills, integrity, and ability to inspire teams'],
      ['What is conflict resolution in teams?', 'Process of resolving disagreements by addressing underlying issues and finding mutually acceptable solutions'],
      ['Explain team dynamics and cohesion', 'The interactions and relationships within a team that affect morale, productivity, and goal achievement'],

      ['LESSON 7: What is organizing in management?', 'Organizing is structuring resources and activities to implement plans and achieve organizational objectives'],
      ['What is organizational structure?', 'Framework showing hierarchical relationships, authority levels, reporting lines, and responsibility distribution'],
      ['What are types of organizational structures?', 'Functional (by department), Divisional (by product/market), Matrix (hybrid), and Network structures'],
      ['Define span of control in organizations', 'Number of direct reports a manager can effectively supervise; affects organizational efficiency'],
      ['What is authority and responsibility?', 'Authority is the right to make decisions; responsibility is the obligation to perform assigned tasks'],
      ['Define centralization vs. decentralization', 'Centralization concentrates decisions at top levels; decentralization distributes authority throughout organization'],
      ['What is departmentalization?', 'Process of grouping related activities and people into departments for coordinated management'],
      ['Explain the chain of command', 'Line of authority and communication flowing from top management to operational levels'],
      ['What is job design in organization?', 'Process of specifying job content, responsibilities, methods, and relationships to achieve organizational goals'],
      ['Define staffing in organizing function', 'Recruiting, selecting, training, and developing human resources to fill organizational positions'],

      ['LESSON 8: What is controlling in management?', 'Controlling is monitoring performance against standards and taking corrective actions to ensure goal achievement'],
      ['What are the steps in the control process?', 'Establish standards → Measure performance → Compare with standards → Take corrective action → Monitor results'],
      ['What types of controls exist?', 'Preventive controls (before problems occur), detective controls (identify problems), and corrective controls (fix problems)'],
      ['Define performance metrics and KPIs', 'Quantifiable measures (Key Performance Indicators) used to assess progress toward organizational objectives'],
      ['What is variance analysis in controlling?', 'Comparison of actual performance against planned performance to identify deviations and causes'],
      ['Explain quality control in engineering', 'Process of ensuring products or services meet defined standards and customer requirements'],
      ['What is budget control in projects?', 'Monitoring actual expenses against budgeted amounts and implementing adjustments to prevent overruns'],
      ['Define schedule control in project management', 'Tracking project progress against timeline and adjusting activities to maintain schedule'],
      ['What is change control in projects?', 'Formal process for evaluating, approving, and implementing changes to project scope or requirements'],
      ['Explain feedback loops in control systems', 'Information flow from monitoring activities back to management for informed decision-making and adjustments'],
      ['What is benchmarking in controls?', 'Comparing organizational performance against industry standards or best-in-class practices for improvement']
    ]
  },

  {
    id: 'builtin-technopreneurship-module-5-6',
    title: 'Technopreneurship Concepts',
    subject: 'Technopreneurship Module 5 & 6',
    description: 'Market analysis, prototyping, MVPs, competitive advantage, and startup strategy.',
    cards: [
      ['What is a visual representation that shows how products or brands are perceived by customers relative to each other in terms of attributes or characteristics?', 'Position Map'],
      ['What refers to the unique qualities or strengths that enable a company to outperform its competitors in the market?', 'Competitive Advantage'],
      ['Which strategic planning tool helps evaluate strengths, weaknesses, opportunities, and threats?', 'SWOT Analysis'],
      ['What is competitive advantage?', 'A condition or circumstance that puts a company in a favorable or superior business position compared to its rivals.'],
      ['What is opportunity assessment?', 'The process of identifying and evaluating potential opportunities to determine their viability and potential for success.'],
      ['What is competitor analysis?', 'The process of identifying and evaluating the strengths and weaknesses of current and potential competitors.'],
      ['What is market sizing?', 'The process of estimating the potential of a market in terms of total revenue or units sold, involving TAM, SAM, and SOM.'],
      ['Define TAM in market sizing.', 'Total Addressable Market – the total possible market for your product or service, without limitations of geography, competition, or distribution.'],
      ['Define SAM in market sizing.', 'Serviceable Addressable Market – the portion of TAM that your product or service can reach given geographical constraints, regulations, and capabilities.'],
      ['Define SOM in market sizing.', 'Serviceable Obtainable Market – the portion of the market you can realistically capture in 2–4 years based on current product, plans, and resources.'],
      ['What is the top-down approach in market sizing?', 'Starts with a large, general market and narrows it down to a specific segment or niche.'],
      ['What is the bottom-up approach in market sizing?', 'Starts with a small, specific market and expands it to a larger, general market.'],
      ['Why is combining top-down and bottom-up approaches beneficial?', 'It enhances accuracy by cross-validating estimates, balancing broad overviews with granular insights, and reducing biases.'],
      ['What are the benefits of market sizing?', 'Identifies demand, ensures efforts are concentrated on greatest opportunities, reveals growth pathways, and highlights potential challenges.'],
      ['What is a prototype?', 'A preliminary version or model of a product, service, or process used to test and validate ideas before final development.'],
      ['What is the main goal of prototyping?', 'To test ideas early, reduce risk, and improve solutions through feedback.'],
      ['What is low-fidelity prototyping?', 'A simple, low-detail prototype used to quickly explore ideas and concepts.'],
      ['What is medium-fidelity prototyping?', 'A more detailed prototype, often digital, that shows structure and basic interactions.'],
      ['What is high-fidelity prototyping?', 'A highly detailed prototype that closely resembles the final product.'],
      ['What does fidelity mean in prototyping?', 'The level of accuracy or similarity of a prototype to the final product.'],
      ['Why should startups avoid over-engineering prototypes?', 'Because prototypes are meant for learning and testing, not final deployment.'],
      ['What is an MVP?', 'A Minimum Viable Product is a product with only essential features to solve a core problem and gather user feedback.'],
      ['Is an MVP a prototype?', 'No, an MVP is a usable product tested with real users, while a prototype is mainly for validation and learning.'],
      ['What is the primary purpose of an MVP?', 'To validate product-market fit using real customer feedback.'],
      ['Why is iteration important in product development?', 'It allows continuous improvement based on feedback and learning.'],
      ['What is opportunity assessment?', 'The process of evaluating whether a business idea is viable and worth pursuing.'],
      ['What is competitive advantage?', 'A condition that enables a business to outperform competitors in the market.'],
      ['What is competitor analysis?', 'The evaluation of competitors’ strengths and weaknesses to improve strategic positioning.'],
      ['Why is competitor analysis critical for startups?', 'It helps reduce risk, identify differentiation, and refine business strategy.'],
      ['What is market sizing?', 'Estimating the total potential market value or demand for a product or service.'],
      ['What does TAM stand for?', 'Total Addressable Market.'],
      ['What does SAM stand for?', 'Serviceable Available Market.'],
      ['What does SOM stand for?', 'Serviceable Obtainable Market.'],
      ['What is a USP?', 'A Unique Selling Proposition that differentiates a product from competitors.'],
      ['Why is a USP important?', 'It helps customers understand why they should choose your product.'],
      ['What is a positioning statement?', 'A statement that defines the target customer, market category, and key value proposition.'],
      ['What is market positioning?', 'How a product is perceived relative to competitors in the minds of customers.'],
      ['What is a competitive positioning map?', 'A visual chart plotting competitors based on key factors like price and quality.'],
      ['Why are X-Y graphs used in competition analysis?', 'To visually compare competitors and identify market gaps.'],
      ['What is a MOAT in business?', 'A sustainable advantage that protects a company from competitors.'],
      ['Who popularized the concept of business MOAT?', 'Investor Warren Buffett.'],
      ['What is a brand moat?', 'Customer loyalty and trust built through strong branding.'],
      ['What is a network effect?', 'When a product becomes more valuable as more people use it.'],
      ['What are switching costs?', 'The effort, time, or money required to change from one product to another.'],
      ['What is intellectual property as a moat?', 'Legal protection that prevents competitors from copying innovations.'],
      ['What are economies of scale?', 'Cost advantages gained by producing at a larger scale.'],
      ['Why is customer feedback important?', 'It guides improvements and ensures solutions meet real user needs.'],
      ['How did INT Technologies handle strong competitors?', 'By focusing on agility, personalized service, and niche markets.'],
      ['What lesson does the INT Technologies case highlight?', 'Adaptability and strategic positioning are critical for survival.'],
      ['Why is continuous competitor research necessary?', 'Markets evolve, and strategies must adapt to remain competitive.'],
      ['What is customer journey mapping?', 'A visual representation of a customer’s experience with a product or service.'],
      ['How does prototyping help investors?', 'It demonstrates feasibility, vision, and early validation.'],
      ['What is the risk of assuming no competition?', 'Customers always have alternatives, including choosing not to buy.']
    ]
  },

  {
    id: 'builtin-technopreneurship',
    title: 'Entrepreneurship in Tech',
    subject: 'Technopreneurship',
    description: 'Core concepts in technology entrepreneurship and startups.',
    cards: [
      ['What is technopreneurship?', 'Entrepreneurship that focuses on technology-based innovations'],
      ['Startup', 'A new business focused on growth and innovation'],
      ['Business model', 'A plan for how a company creates, delivers, and captures value'],
      ['Pitch deck', 'A presentation to attract investors to a startup'],
      ['Innovation', 'Developing new ideas, products, or services'],
      ['Funding', 'Securing financial resources to grow a business'],
      ['Market research', 'Studying market needs, trends, and competitors'],
      ['Product development', 'Designing and building a product from concept to launch'],
      ['Entrepreneurial mindset', 'Thinking creatively, taking risks, and solving problems'],
      ['Scaling a business', 'Growing a startup efficiently to reach more customers'],
      ['Lean startup', 'A methodology for developing businesses quickly with minimal waste'],
      ['Value proposition', 'The unique value a product or service provides to customers'],
      ['Customer validation', 'Testing assumptions by getting feedback from real users'],
      ['Revenue streams', 'Ways a business generates income'],
      ['Intellectual property', 'Protecting innovations through patents, copyrights, or trademarks'],
      ['Business plan', 'A formal document detailing business goals and strategies'],
      ['Networking', 'Building professional connections to support growth'],
      ['Competition analysis', 'Studying competitors to identify advantages and threats'],
      ['Technology adoption', 'Implementing new tech to improve products or services'],
      ['Exit strategy', 'Plan for how a founder or investor will leave the business profitably']
    ]
  },

  {
    id: 'builtin-thesis-outline',
    title: 'Electronics Engineering Topics',
    subject: 'Thesis Outline Topics',
    description: 'Essential topics for preparing an Electronics Engineering thesis.',
    cards: [
      ['Thesis purpose', 'To investigate, analyze, and present findings on a technical problem'],
      ['Title selection', 'Choosing a concise and relevant topic for research'],
      ['Abstract', 'A summary of the research, methodology, and results'],
      ['Introduction', 'Background information and problem statement'],
      ['Literature review', 'Survey of existing studies related to the research topic'],
      ['Methodology', 'Detailed plan of how the research is conducted'],
      ['Results', 'Presentation of data and findings'],
      ['Discussion', 'Interpretation and analysis of the results'],
      ['Conclusion', 'Summary of findings and recommendations'],
      ['References', 'List of all sources cited in the research'],
      ['Problem statement', 'The specific issue or question the research addresses'],
      ['Scope and limitations', 'Defines boundaries and constraints of the research'],
      ['Research objectives', 'Specific goals the research aims to achieve'],
      ['Hypothesis formulation', 'Creating a testable prediction based on theory'],
      ['Data collection methods', 'Techniques for gathering research data'],
      ['Analysis techniques', 'Methods for interpreting and processing data'],
      ['Figures and tables', 'Visual representations of data in the thesis'],
      ['Appendices', 'Supplementary materials provided at the end of the thesis'],
      ['Acknowledgments', 'Section to thank contributors and mentors'],
      ['Future work', 'Suggestions for research or development beyond the current study']
    ]
  },


  {
    id: 'builtin-electronics-circuit-analysis',
    title: 'Circuit Analysis',
    subject: 'Electronics Engineering',
    description: 'Core electrical and electronic circuit concepts, laws, components, and analysis methods.',
    cards: [
      ['Ohm’s Law', 'V = IR, where V is voltage, I is current, and R is resistance'],
      ['Kirchhoff’s Current Law (KCL)', 'The algebraic sum of currents entering and leaving a node is zero; current entering a node equals current leaving it'],
      ['Kirchhoff’s Voltage Law (KVL)', 'The algebraic sum of all voltages around a closed loop is zero'],
      ['What is voltage?', 'Electrical potential difference between two points, measured in volts (V)'],
      ['What is current?', 'The rate of flow of electric charge, measured in amperes (A)'],
      ['What is resistance?', 'Opposition to current flow, measured in ohms (Ω)'],
      ['What is conductance?', 'The reciprocal of resistance, G = 1/R, measured in siemens (S)'],
      ['Electrical power', 'P = VI; for a resistor, P = I²R = V²/R'],
      ['Electrical energy', 'Energy consumed or delivered over time; E = Pt'],
      ['Series circuit', 'A circuit in which components share the same current path'],
      ['Parallel circuit', 'A circuit in which components are connected across the same two nodes and share the same voltage'],
      ['Equivalent resistance in series', 'Req = R1 + R2 + ... + Rn'],
      ['Equivalent resistance in parallel', '1/Req = 1/R1 + 1/R2 + ... + 1/Rn'],
      ['Voltage divider', 'A circuit that produces a fraction of an input voltage using series resistors'],
      ['Voltage divider equation', 'Vout = Vin × R2/(R1 + R2) for the basic two-resistor divider'],
      ['Current divider', 'A parallel-resistor network that divides current among its branches'],
      ['What is a node?', 'A point or group of directly connected points having the same electrical potential'],
      ['What is a branch?', 'A single element or path between two nodes'],
      ['What is a mesh?', 'A loop in a planar circuit that contains no other loop inside it'],
      ['Superposition theorem', 'In a linear circuit, the total response equals the sum of the responses produced by each independent source acting alone'],
      ['Thevenin’s theorem', 'A linear two-terminal network can be represented by an equivalent voltage source in series with an equivalent resistance'],
      ['Norton’s theorem', 'A linear two-terminal network can be represented by an equivalent current source in parallel with an equivalent resistance'],
      ['Maximum power transfer theorem', 'Maximum power is delivered to a resistive load when the load resistance equals the Thevenin resistance seen by the load'],
      ['Open circuit', 'A condition in which the current through a branch is ideally zero'],
      ['Short circuit', 'A connection with ideally zero resistance that can allow very large current depending on the source and circuit impedance']
    ]
  },

  {
    id: 'builtin-electronics-components',
    title: 'Electronic Components',
    subject: 'Electronics Engineering',
    description: 'Common passive and active electronic components and their functions.',
    cards: [
      ['Resistor', 'A passive component that limits current and develops a voltage according to Ohm’s Law'],
      ['Capacitor', 'A component that stores electrical energy in an electric field'],
      ['Inductor', 'A component that stores energy in a magnetic field and opposes changes in current'],
      ['Diode', 'A semiconductor device that primarily allows current to flow in one direction'],
      ['LED', 'Light-emitting diode that produces light when forward biased'],
      ['Zener diode', 'A diode designed to operate in reverse breakdown for voltage regulation or reference applications'],
      ['Photodiode', 'A light-sensitive semiconductor device that converts incident light into electrical current'],
      ['Transistor', 'A semiconductor device used for switching, amplification, and signal control'],
      ['BJT', 'Bipolar Junction Transistor; a current-controlled transistor with emitter, base, and collector terminals'],
      ['NPN transistor', 'A BJT commonly used with conventional current flowing from collector toward emitter when forward biased and active'],
      ['PNP transistor', 'A BJT with opposite polarity relationships to an NPN transistor'],
      ['MOSFET', 'A voltage-controlled field-effect transistor with gate, source, and drain terminals'],
      ['N-channel MOSFET', 'A MOSFET in which conduction is primarily through an n-type channel'],
      ['P-channel MOSFET', 'A MOSFET in which conduction is primarily through a p-type channel'],
      ['Operational amplifier', 'A high-gain differential amplifier commonly used for amplification, filtering, comparison, and signal conditioning'],
      ['Relay', 'An electrically operated switch that uses a coil to control contacts'],
      ['Transformer', 'A magnetic component that transfers AC energy between windings and can step voltage up or down'],
      ['Potentiometer', 'A variable resistor commonly used as an adjustable voltage divider'],
      ['Thermistor', 'A temperature-sensitive resistor whose resistance changes significantly with temperature'],
      ['LDR', 'Light-dependent resistor whose resistance changes with incident light intensity'],
      ['Fuse', 'A protective device designed to open a circuit when excessive current causes its element to melt'],
      ['Switch', 'A device that opens, closes, or changes an electrical connection'],
      ['Battery', 'A source of electrical energy that provides a DC voltage through electrochemical reactions'],
      ['Voltage regulator', 'A circuit or device that maintains a desired output voltage despite changes in input or load conditions']
    ]
  },

  {
    id: 'builtin-semiconductor-electronics',
    title: 'Semiconductor Devices',
    subject: 'Electronics Engineering',
    description: 'Semiconductor fundamentals, PN junctions, diodes, transistors, and biasing.',
    cards: [
      ['What is a semiconductor?', 'A material whose electrical conductivity lies between that of a conductor and an insulator and can be controlled by impurities, temperature, and electric fields'],
      ['Common semiconductor materials', 'Silicon and germanium are common elemental semiconductor materials; compound semiconductors include materials such as GaAs'],
      ['Intrinsic semiconductor', 'A relatively pure semiconductor whose carrier concentration is determined mainly by the material and temperature'],
      ['Extrinsic semiconductor', 'A semiconductor whose electrical properties have been modified by intentional doping'],
      ['N-type semiconductor', 'A doped semiconductor in which electrons are the majority carriers'],
      ['P-type semiconductor', 'A doped semiconductor in which holes are the majority carriers'],
      ['Majority carrier', 'The type of charge carrier present in greater concentration in a doped semiconductor'],
      ['Minority carrier', 'The type of charge carrier present in lower concentration in a doped semiconductor'],
      ['PN junction', 'The boundary formed when P-type and N-type semiconductor regions are joined'],
      ['Depletion region', 'The region around a PN junction depleted of mobile majority carriers and containing fixed ionized dopants'],
      ['Forward bias', 'A diode bias condition that reduces the depletion barrier and permits significant forward current'],
      ['Reverse bias', 'A diode bias condition that increases the depletion barrier and normally produces only small leakage current'],
      ['Diode forward voltage', 'The forward voltage associated with significant conduction; its value depends on diode technology and operating current'],
      ['Reverse breakdown', 'A condition in which reverse current increases strongly after the reverse voltage exceeds a breakdown level'],
      ['BJT biasing', 'Setting appropriate DC voltages and currents to establish the transistor operating point'],
      ['Q-point', 'The quiescent operating point of a transistor, usually defined by its DC current and voltage values'],
      ['Transistor cutoff', 'A BJT operating region in which collector current is ideally near zero'],
      ['Transistor saturation', 'A BJT operating region in which both junctions are forward biased and the transistor is strongly conducting'],
      ['MOSFET threshold voltage', 'The approximate gate-to-source voltage at which a conductive channel begins to form under specified conditions'],
      ['CMOS', 'Complementary Metal-Oxide-Semiconductor technology using complementary MOSFETs, widely used in digital integrated circuits']
    ]
  },

  {
    id: 'builtin-digital-electronics',
    title: 'Digital Electronics',
    subject: 'Electronics Engineering',
    description: 'Logic gates, Boolean algebra, combinational and sequential digital circuits.',
    cards: [
      ['Analog signal', 'A continuously varying signal that can take values over a continuous range'],
      ['Digital signal', 'A signal represented using discrete levels or states'],
      ['Binary number system', 'A base-2 number system using the digits 0 and 1'],
      ['Logic HIGH', 'A digital logic state represented by a voltage range interpreted as 1'],
      ['Logic LOW', 'A digital logic state represented by a voltage range interpreted as 0'],
      ['AND gate', 'Outputs 1 only when all inputs are 1'],
      ['OR gate', 'Outputs 1 when at least one input is 1'],
      ['NOT gate', 'Inverts a logic input: 1 becomes 0 and 0 becomes 1'],
      ['NAND gate', 'The inverse of the AND operation'],
      ['NOR gate', 'The inverse of the OR operation'],
      ['XOR gate', 'Outputs 1 when the inputs are different'],
      ['XNOR gate', 'Outputs 1 when the inputs are the same'],
      ['Universal gate', 'A gate from which any Boolean logic function can be constructed; NAND and NOR are universal gates'],
      ['Boolean algebra', 'A mathematical system used to represent and simplify logical relationships'],
      ['De Morgan’s theorem', 'Rules relating complements of AND and OR expressions: NOT(A·B)=NOT A + NOT B and NOT(A+B)=NOT A·NOT B'],
      ['Truth table', 'A table showing all possible input combinations and their corresponding outputs'],
      ['Combinational circuit', 'A digital circuit whose output depends on the present input values'],
      ['Sequential circuit', 'A digital circuit whose output depends on present inputs and stored previous state'],
      ['Flip-flop', 'A bistable sequential circuit capable of storing one bit'],
      ['D flip-flop', 'A flip-flop that stores the input data value according to its clocking behavior'],
      ['JK flip-flop', 'A flip-flop that can hold, set, reset, or toggle depending on J and K inputs'],
      ['Counter', 'A sequential circuit that progresses through a defined sequence of states in response to clock pulses'],
      ['Register', 'A group of flip-flops used to store and manipulate multiple bits'],
      ['Multiplexer', 'A digital circuit that selects one of multiple inputs and routes it to a single output'],
      ['Demultiplexer', 'A digital circuit that routes one input to one of multiple outputs'],
      ['Encoder', 'A circuit that converts one active input among many into a coded binary output'],
      ['Decoder', 'A circuit that converts a binary code into one or more selected outputs'],
      ['ADC', 'Analog-to-Digital Converter that converts an analog quantity into a digital representation'],
      ['DAC', 'Digital-to-Analog Converter that converts a digital code into an analog output']
    ]
  },

  {
    id: 'builtin-microcontrollers-embedded',
    title: 'Microcontrollers & Embedded Systems',
    subject: 'Electronics Engineering',
    description: 'Microcontrollers, embedded systems, GPIO, timers, interrupts, and common communication interfaces.',
    cards: [
      ['Microcontroller', 'An integrated circuit containing a processor, memory, and peripherals for embedded control applications'],
      ['Microprocessor', 'A processor-centered integrated circuit that typically relies on external memory and peripherals'],
      ['Embedded system', 'A computer-based system designed to perform a specific function within a larger device or product'],
      ['GPIO', 'General-Purpose Input/Output pins used to interface a microcontroller with external digital devices'],
      ['Digital input', 'A microcontroller input that detects discrete logic states'],
      ['Digital output', 'A microcontroller output that drives a digital logic level'],
      ['PWM', 'Pulse Width Modulation; varying pulse duty cycle to control average power or represent information'],
      ['Duty cycle', 'The percentage of one period during which a periodic signal is active or high'],
      ['ADC resolution', 'The number of discrete digital levels available to represent an analog input'],
      ['Interrupt', 'A mechanism that temporarily redirects processor execution to handle an event'],
      ['Interrupt Service Routine', 'The function or routine executed in response to an interrupt'],
      ['Timer', 'A peripheral used to measure time intervals, generate delays, or produce periodic events'],
      ['UART', 'Universal Asynchronous Receiver/Transmitter communication interface commonly used for serial communication'],
      ['I2C', 'Two-wire synchronous serial communication bus using SDA for data and SCL for clock'],
      ['SPI', 'Synchronous serial interface commonly using clock, MOSI, MISO, and chip-select signals'],
      ['CAN bus', 'A robust multi-master communication bus widely used in automotive and industrial systems'],
      ['Watchdog timer', 'A timer that can reset or recover a system if software fails to operate correctly'],
      ['Firmware', 'Software stored in or associated with embedded hardware that controls its operation'],
      ['Bootloader', 'A program responsible for initializing a device and/or loading application firmware'],
      ['Real-time system', 'A system in which correctness depends on producing results within required timing constraints'],
      ['Debouncing', 'A technique used to prevent mechanical switch contact bounce from being interpreted as multiple input events'],
      ['Pull-up resistor', 'A resistor that biases a digital signal toward the supply voltage when no active driver is present'],
      ['Pull-down resistor', 'A resistor that biases a digital signal toward ground when no active driver is present']
    ]
  },

  {
    id: 'builtin-signals-communications',
    title: 'Signals & Communications',
    subject: 'Electronics Engineering',
    description: 'Signals, Fourier concepts, modulation, bandwidth, sampling, and communication systems.',
    cards: [
      ['What is a signal?', 'A physical quantity that carries information and varies with time, space, or another independent variable'],
      ['Continuous-time signal', 'A signal defined for every value of continuous time'],
      ['Discrete-time signal', 'A signal defined only at discrete time instants'],
      ['Periodic signal', 'A signal that repeats itself after a fixed period T'],
      ['Frequency', 'The number of cycles per second, measured in hertz (Hz)'],
      ['Angular frequency', 'ω = 2πf, measured in radians per second'],
      ['Amplitude', 'The magnitude of a signal relative to a reference or equilibrium level'],
      ['Phase', 'The angular position or relative shift of a sinusoidal waveform'],
      ['RMS value', 'The root-mean-square value that represents the equivalent heating effect of an AC quantity in a resistor'],
      ['Fourier series', 'Representation of a periodic signal as a sum of sinusoids at harmonic frequencies'],
      ['Fourier transform', 'A mathematical transformation that represents a signal in the frequency domain'],
      ['Sampling', 'Converting a continuous-time signal into discrete-time samples at specified intervals'],
      ['Nyquist sampling theorem', 'A band-limited signal can be reconstructed from uniform samples when the sampling frequency is greater than twice its highest frequency component'],
      ['Aliasing', 'Distortion caused when a signal is sampled below the required sampling rate'],
      ['Bandwidth', 'The range of frequencies occupied by or allocated to a signal or system'],
      ['Carrier signal', 'A higher-frequency signal whose properties are varied to convey information'],
      ['Modulation', 'The process of varying a carrier parameter according to an information signal'],
      ['AM', 'Amplitude Modulation, where the carrier amplitude is varied according to the message signal'],
      ['FM', 'Frequency Modulation, where the carrier frequency varies according to the message signal'],
      ['PM', 'Phase Modulation, where the carrier phase varies according to the message signal'],
      ['Demodulation', 'Recovering the information signal from a modulated carrier'],
      ['Noise', 'Unwanted random or interfering electrical energy that can degrade a signal'],
      ['SNR', 'Signal-to-Noise Ratio; the ratio of desired signal power to noise power, commonly expressed in decibels'],
      ['Decibel', 'A logarithmic unit used to express ratios such as power gain or attenuation'],
      ['Antenna', 'A device that converts electrical signals to electromagnetic waves or vice versa']
    ]
  },

  {
    id: 'builtin-instrumentation-measurement',
    title: 'Instrumentation & Measurements',
    subject: 'Electronics Engineering',
    description: 'Electronic measurement instruments, accuracy, precision, sensors, and signal conditioning.',
    cards: [
      ['Multimeter', 'An instrument used to measure quantities such as voltage, current, resistance, and continuity'],
      ['Oscilloscope', 'An instrument used to visualize voltage or other electrical signals as a function of time'],
      ['Function generator', 'An instrument that generates electrical waveforms such as sine, square, and triangle waves'],
      ['Power supply', 'A device that provides electrical power at specified voltage and current conditions'],
      ['Voltmeter', 'An instrument used to measure voltage between two points'],
      ['Ammeter', 'An instrument used to measure electric current'],
      ['Ohmmeter', 'An instrument used to measure electrical resistance'],
      ['Accuracy', 'How close a measurement is to the true or accepted value'],
      ['Precision', 'How closely repeated measurements agree with one another'],
      ['Resolution', 'The smallest change in a measured quantity that an instrument can distinguish'],
      ['Sensitivity', 'The change in output produced per unit change in the measured input'],
      ['Calibration', 'Comparison and adjustment of an instrument against a known reference standard'],
      ['Measurement error', 'The difference between a measured value and the accepted or reference value'],
      ['Sensor', 'A device that detects a physical quantity and produces a corresponding signal'],
      ['Actuator', 'A device that converts a control signal into physical action'],
      ['Signal conditioning', 'Processing a sensor signal through functions such as amplification, filtering, isolation, or level shifting'],
      ['Instrumentation amplifier', 'A precision differential amplifier designed for accurate measurement of small voltage differences'],
      ['Low-pass filter', 'A filter that passes lower frequencies while attenuating frequencies above its cutoff region'],
      ['High-pass filter', 'A filter that passes higher frequencies while attenuating frequencies below its cutoff region'],
      ['Band-pass filter', 'A filter that passes a selected range of frequencies while attenuating frequencies outside the band'],
      ['Notch filter', 'A filter designed to strongly attenuate a narrow frequency range'],
      ['Thermocouple', 'A temperature sensor based on a voltage generated by the junction of dissimilar conductors'],
      ['RTD', 'Resistance Temperature Detector; a temperature sensor whose resistance changes predictably with temperature'],
      ['Strain gauge', 'A resistive sensor whose resistance changes when mechanically strained'],
      ['LVDT', 'Linear Variable Differential Transformer, a sensor used to measure linear displacement']
    ]
  },

  {
    id: 'builtin-pcb-embedded-design',
    title: 'PCB & Electronics Design',
    subject: 'Electronics Engineering',
    description: 'Printed circuit boards, schematic design, layout, grounding, soldering, and design-for-manufacturing concepts.',
    cards: [
      ['PCB', 'Printed Circuit Board that mechanically supports and electrically connects electronic components'],
      ['Schematic', 'A symbolic diagram showing the electrical relationships and connections in a circuit'],
      ['PCB layout', 'The physical arrangement of components, copper traces, vias, planes, and other board features'],
      ['Trace', 'A conductive path on a PCB used to electrically connect circuit nodes'],
      ['Via', 'A plated hole or conductive structure that electrically connects different PCB layers'],
      ['Ground plane', 'A large conductive PCB region used as a common reference and low-impedance return path'],
      ['Power plane', 'A conductive plane used to distribute a supply voltage across a PCB'],
      ['Copper pour', 'A filled copper region used for power distribution, grounding, shielding, or thermal purposes'],
      ['Silkscreen', 'Printed markings on a PCB used for reference designators, labels, polarity, and assembly information'],
      ['Solder mask', 'The protective insulating coating applied to PCB surfaces except where soldering is intended'],
      ['Through-hole component', 'A component whose leads pass through holes in the PCB'],
      ['SMD', 'Surface-Mount Device designed to be mounted directly on PCB pads'],
      ['Footprint', 'The PCB land pattern and mechanical outline associated with a component package'],
      ['DRC', 'Design Rule Check that verifies PCB layout constraints such as clearances and routing rules'],
      ['ERC', 'Electrical Rule Check that identifies possible electrical issues in a schematic'],
      ['Decoupling capacitor', 'A capacitor placed near an IC power pin to reduce local supply noise and transient voltage variations'],
      ['Ground loop', 'An unwanted current path involving multiple ground connections that can introduce noise or interference'],
      ['EMI', 'Electromagnetic Interference that can disrupt electronic circuits or communication'],
      ['ESD', 'Electrostatic Discharge that can damage or disturb sensitive electronic components'],
      ['Thermal management', 'Methods used to control component temperature and remove heat from electronic systems'],
      ['Heat sink', 'A component that transfers heat from a device to the surrounding environment'],
      ['Design for Manufacturability', 'Designing a product so it can be manufactured reliably, efficiently, and economically'],
      ['Design for Testability', 'Designing hardware so important functions and nodes can be tested efficiently during production or maintenance']
    ]
  },

  {
    id: 'builtin-control-electronics',
    title: 'Control Systems',
    subject: 'Electronics Engineering',
    description: 'Feedback, transfer functions, stability, controllers, and basic control-system concepts.',
    cards: [
      ['Control system', 'A system that manages or regulates a process to achieve a desired output'],
      ['Open-loop control', 'A control system that does not use feedback from the output to adjust the input'],
      ['Closed-loop control', 'A control system that uses feedback to compare the output with the desired reference'],
      ['Feedback', 'Returning a portion of a system output to its input for control or regulation'],
      ['Reference input', 'The desired value or command that a control system attempts to achieve'],
      ['Error signal', 'The difference between the reference input and the measured feedback signal'],
      ['Plant', 'The physical process or system being controlled'],
      ['Controller', 'A device or algorithm that generates a control action based on system conditions'],
      ['Transfer function', 'The ratio of output to input in the Laplace domain under zero initial conditions'],
      ['Stability', 'The property of a system in which its response remains bounded under appropriate bounded inputs'],
      ['PID controller', 'A controller combining proportional, integral, and derivative actions'],
      ['Proportional control', 'Control action proportional to the current error'],
      ['Integral control', 'Control action based on the accumulated error over time'],
      ['Derivative control', 'Control action based on the rate of change of error'],
      ['Steady-state error', 'The remaining difference between desired and actual output after transient effects have settled'],
      ['Transient response', 'The portion of a system response associated with the transition toward steady state'],
      ['Overshoot', 'The amount by which a response exceeds its final steady-state value'],
      ['Settling time', 'The time required for a response to remain within a specified tolerance band around its final value'],
      ['Rise time', 'The time required for a response to move between specified lower and upper percentages of its final value'],
      ['Feedback gain', 'The gain applied in the feedback path of a control system']
    ]
  },

  {
    id: 'builtin-electronics-power',
    title: 'Power Electronics',
    subject: 'Electronics Engineering',
    description: 'Power semiconductor devices, rectifiers, converters, switching, and power control.',
    cards: [
      ['Power electronics', 'The application of semiconductor devices to control and convert electrical power'],
      ['Rectifier', 'A circuit that converts AC into DC'],
      ['Half-wave rectifier', 'A rectifier that uses one half-cycle of an AC input'],
      ['Full-wave rectifier', 'A rectifier that uses both half-cycles of an AC input'],
      ['Bridge rectifier', 'A full-wave rectifier commonly implemented with four diodes'],
      ['Filter capacitor', 'A capacitor used after rectification to reduce ripple in a DC output'],
      ['Ripple voltage', 'The residual periodic AC variation present on a rectified or regulated DC output'],
      ['Buck converter', 'A switching DC-DC converter that steps voltage down'],
      ['Boost converter', 'A switching DC-DC converter that steps voltage up'],
      ['Buck-boost converter', 'A switching converter capable of producing an output magnitude that can be higher or lower than the input, depending on topology and control'],
      ['Inverter', 'A power electronic converter that converts DC into AC'],
      ['Switching frequency', 'The frequency at which a power semiconductor is switched on and off'],
      ['Duty cycle in a converter', 'The fraction of each switching period for which the controlled switch is on'],
      ['IGBT', 'Insulated Gate Bipolar Transistor combining a MOS-gated input with bipolar conduction characteristics'],
      ['SCR', 'Silicon Controlled Rectifier, a thyristor that can be triggered into conduction and remains on under appropriate current conditions'],
      ['TRIAC', 'A bidirectional thyristor device commonly used for AC power control'],
      ['MOSFET in power electronics', 'A fast-switching transistor widely used for low- to medium-voltage power conversion'],
      ['Snubber circuit', 'A circuit used to control voltage/current transients and reduce stress or switching noise'],
      ['Efficiency', 'The ratio of useful output power to input power, commonly expressed as a percentage'],
      ['Inrush current', 'The temporary high current drawn when a circuit or equipment is initially energized']
    ]
  },

  {
    id: 'builtin-electronics-engineering-practice',
    title: 'Electronics Engineering Practice',
    subject: 'Electronics Engineering',
    description: 'Practical engineering, safety, troubleshooting, documentation, and professional electronics concepts.',
    cards: [
      ['What is troubleshooting?', 'A systematic process of identifying, isolating, and correcting faults in an electronic system'],
      ['First step in troubleshooting', 'Understand the expected operation and verify the symptoms before changing components'],
      ['Divide-and-conquer troubleshooting', 'A method of isolating faults by testing sections of a system and narrowing the possible fault location'],
      ['Continuity test', 'A test used to determine whether a low-resistance electrical path exists between two points'],
      ['Cold solder joint', 'A solder connection with poor bonding, often caused by insufficient heating, contamination, or movement during soldering'],
      ['Solder bridge', 'An unintended solder connection between adjacent pads or conductors'],
      ['Polarity', 'The positive and negative orientation that must be observed for polarity-sensitive components and power connections'],
      ['ESD protection', 'Practices and equipment used to prevent electrostatic discharge from damaging sensitive electronics'],
      ['Grounding', 'Connecting a circuit or equipment to a defined reference or protective earth as required by the system design'],
      ['Electrical isolation', 'Separating circuits so there is no direct conductive path between them, often using transformers or optocouplers'],
      ['Optocoupler', 'A component that transfers a signal between electrically isolated circuits using light'],
      ['Datasheet', 'A manufacturer document containing specifications, pinouts, electrical characteristics, ratings, and application information'],
      ['Absolute maximum rating', 'A manufacturer-specified limit that should not be exceeded because doing so may damage the device'],
      ['Derating', 'Operating a component below its maximum rating to improve reliability and account for environmental conditions'],
      ['Tolerance', 'The permitted variation of a component value from its nominal specification'],
      ['BOM', 'Bill of Materials; a list of components and quantities required to build a product or assembly'],
      ['Reference designator', 'A label identifying a component on a schematic or PCB, such as R1, C1, D1, or U1'],
      ['Netlist', 'A description of the electrical connections between component pins or terminals'],
      ['Design verification', 'The process of checking whether a design meets specified technical requirements'],
      ['Prototype testing', 'Testing an early hardware implementation to identify problems and validate intended operation'],
      ['Engineering safety', 'Practices that reduce electrical, thermal, mechanical, and other hazards during design, testing, and operation']
    ]
  },

  {
    id: 'builtin-geography',
    title: 'Basic Geography',
    subject: 'Geography',
    description: 'Basic geography facts and concepts.',
    cards: [
      ['Largest continent?', 'Asia'],
      ['Longest river in the world?', 'Nile'],
      ['Largest ocean?', 'Pacific'],
      ['Highest mountain?', 'Mount Everest'],
      ['Capital of France?', 'Paris'],
      ['Country with most population?', 'China'],
      ['Continent Australia is in?', 'Oceania'],
      ['Imaginary line dividing Earth into N and S?', 'Equator'],
      ['Largest desert?', 'Sahara'],
      ['What is tectonic plate movement called?', 'Plate tectonics']
    ]
  },

  {
    id: 'builtin-chemistry',
    title: 'Basic Chemistry',
    subject: 'Chemistry',
    description: 'Basic chemistry concepts and terminology.',
    cards: [
      ['Water formula?', 'H2O'],
      ['Atomic number?', 'Number of protons'],
      ['pH of pure water?', '7'],
      ['Most abundant gas in air?', 'Nitrogen'],
      ['Chemical symbol for gold?', 'Au'],
      ['Process of solid to gas?', 'Sublimation'],
      ['Acidic solution has pH?', '<7'],
      ['Base solution has pH?', '>7'],
      ['Covalent bond?', 'Sharing of electrons'],
      ['Ionic bond?', 'Transfer of electrons']
    ]
  },

  {
    id: 'builtin-physics',
    title: 'Basic Physics',
    subject: 'Physics',
    description: 'Basic physics formulas, units, and principles.',
    cards: [
      ['Force formula?', 'F = ma'],
      ['Speed formula?', 'Distance ÷ Time'],
      ['Acceleration formula?', 'Change in velocity ÷ Time'],
      ['Unit of energy?', 'Joule'],
      ['Unit of force?', 'Newton'],
      ['Unit of power?', 'Watt'],
      ['Gravity acceleration?', '9.8 m/s²'],
      ['Light speed?', '3 × 10⁸ m/s'],
      ["Newton's 1st law?", 'Inertia'],
      ["Newton's 2nd law?", 'F = ma']
    ]
  },

  {
    id: 'builtin-art',
    title: 'Basic Art',
    subject: 'Art',
    description: 'Basic art concepts, techniques, and famous artists.',
    cards: [
      ['Primary colors?', 'Red, Blue, Yellow'],
      ['Famous painter of Mona Lisa?', 'Leonardo da Vinci'],
      ['Art of making sculptures?', 'Sculpture'],
      ['Famous Dutch painter of Starry Night?', 'Vincent van Gogh'],
      ['Technique of shading?', 'Hatching'],
      ['Mixing colors?', 'Color theory'],
      ['Modern art style using geometric shapes?', 'Cubism'],
      ['Art of decorative writing?', 'Calligraphy'],
      ['Famous Mexican muralist?', 'Diego Rivera'],
      ['Art movement with surreal imagery?', 'Surrealism']
    ]
  }
];