import type { McuRuntimeInputs, McuRuntimeState, McuPinEvent, PersistentMcuRuntime, McuGlobalValue, PinMode } from "./mcu-runtime";

type Value = number | boolean | string | Value[];
type Token = { kind:"id"|"num"|"str"|"op"|"eof"; value:string };
type Fn = { params:string[]; body:Token[] };

function lex(src:string):Token[]{const a:Token[]=[];let i=0;const ops=["==","!=","<=",">=","&&","||","++","--","+=","-=","*=","/=","%=","<<",">>"];while(i<src.length){const c=src[i];if(/\s/.test(c)){i++;continue}if(c==='"'){let j=i+1,v="";while(j<src.length&&src[j]!=='"'){if(src[j]==='\\'&&j+1<src.length){const q=src[j+1];v+=q==='n'?"\n":q==='r'?"\r":q==='t'?"\t":q;j+=2}else v+=src[j++]}a.push({kind:"str",value:v});i=j+1;continue}if(c==="'"){let j=i+1,v=src[j]??"";if(v==='\\'&&j+1<src.length)v=src[++j]??"";a.push({kind:"num",value:String(v.charCodeAt(0)||0)});i=j+1;while(src[i]&&src[i]!=="'")i++;if(src[i]==="'")i++;continue}const n=src.slice(i).match(/^(?:0[xX][0-9a-fA-F]+|0[bB][01]+|[0-9]+(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?)/);if(n){let v=n[0];if(/^0[bB]/.test(v))v=String(parseInt(v.slice(2),2));else if(/^0[xX]/.test(v))v=String(parseInt(v,16));a.push({kind:"num",value:v});i+=n[0].length;continue}const id=src.slice(i).match(/^[A-Za-z_]\w*/);if(id){let v=id[0];if(/^B[01]{1,8}$/.test(v))a.push({kind:"num",value:String(parseInt(v.slice(1),2))});else a.push({kind:"id",value:v});i+=v.length;continue}const op=ops.find(x=>src.startsWith(x,i))??c;a.push({kind:"op",value:op});i+=op.length}a.push({kind:"eof",value:"eof"});return a}

function normalizeMembers(src:string){return src.replace(/\b(lcd|display|u8g2)\s*\.\s*([A-Za-z_]\w*)\s*\(/g,(_,o,m)=>`${o}_${m}(`)}

class Interpreter{
 t:Token[]=[];p=0;f=new Map<string,Fn>();env:Record<string,Value>; arrays=new Map<string,Value[]>(); lcdCol=0;lcdRow=0;lcdCols=16;lcdRows=2; chars:Record<number,number[]>={}; stopped=false;
 constructor(public source:string,public state:McuRuntimeState,public runtime:PersistentMcuRuntime,public inputs:McuRuntimeInputs,public events:McuPinEvent[]){this.env=runtime.globals as Record<string,Value>}
 run(){this.t=lex(normalizeMembers(this.source));this.seedGlobals();this.extract();this.state.lcdPins=this.parseLcd()??this.state.lcdPins;const dig=this.inputs.digital??{};for(const [pin,value] of Object.entries(dig)){if((this.state.modes[pin]??"INPUT")!=="OUTPUT")this.state.digital[pin]=value}for(const [pin,mode] of Object.entries(this.state.modes)){if(mode==="INPUT_PULLUP"&&!(pin in dig))this.state.digital[pin]=1}if(!this.runtime.setupComplete&&this.f.has("setup")){this.call("setup",[]);this.runtime.setupComplete=true}if(this.f.has("loop")&&!this.stopped)this.call("loop",[])}
 seedGlobals(){
  const scalar=/\b(?:const\s+)?(?:unsigned\s+long|unsigned\s+int|int|long|bool|boolean|byte|float|double|char|String)\s+([A-Za-z_]\w*)\s*=\s*([^;]+);/g; let m:RegExpExecArray|null;
  while((m=scalar.exec(this.source))){const n=m[1];if(n in this.env)continue;const e=m[2].trim();if(/^B[01]{1,8}$/.test(e))this.env[n]=parseInt(e.slice(1),2);else if(/^[-+]?\d+(?:\.\d+)?$/.test(e))this.env[n]=Number(e);else if(/^".*"$/.test(e))this.env[n]=e.slice(1,-1);else this.env[n]=Number(this.env[e]??0);}
  const arr=/\b(?:const\s+)?(?:byte|int|char)\s+([A-Za-z_]\w*)\s*\[\s*\d+\s*\]\s*=\s*\{([^}]*)\}/gs;
  while((m=arr.exec(this.source))){const vals=m[2].split(",").map(x=>{const e=x.trim();return /^B[01]{1,8}$/.test(e)?parseInt(e.slice(1),2):Number(e)||0});this.arrays.set(m[1],vals);this.env[m[1]]=vals;}
 }
 parseLcd(){const m=this.source.match(/LiquidCrystal\s+\w+\s*\(\s*([^,]+),\s*([^,]+),\s*([^,]+),\s*([^,]+),\s*([^,]+),\s*([^)]+)\)/i);if(!m)return undefined;const pin=(x:string)=>/^\d+$/.test(x.trim())?`d${x.trim()}`:x.trim().toLowerCase();return{rs:pin(m[1]),e:pin(m[2]),d4:pin(m[3]),d5:pin(m[4]),d6:pin(m[5]),d7:pin(m[6])}}
 extract(){const type=new Set(["void","int","long","unsigned","bool","boolean","byte","float","double","char","String","static","const"]);let i=0;while(i<this.t.length-1){if(this.t[i].kind!=="id"){i++;continue}let j=i;if(type.has(this.t[j].value)){while(j<this.t.length&&this.t[j].kind==="id"&&type.has(this.t[j].value))j++;if(this.t[j]?.kind!=="id"){i++;continue}}else{ i++;continue }const name=this.t[j].value;if(this.t[j+1]?.value!=="("){i++;continue}let k=j+2,d=1,params:string[]=[];while(k<this.t.length&&d){if(this.t[k].value==="(")d++;else if(this.t[k].value===")"){d--;if(d===0)break}else if(d===1&&this.t[k].kind==="id"&&this.t[k].value!=="const"){params.push(this.t[k].value);if(params.length>1)params[params.length-1]=this.t[k].value}k++}if(this.t[k+1]?.value!=="{"){i++;continue}let b=k+2,bd=1;while(b<this.t.length&&bd){if(this.t[b].value==="{")bd++;else if(this.t[b].value=== "}")bd--;b++}this.f.set(name,{params:params.filter((x,idx)=>idx===0||x!==params[idx-1]),body:this.t.slice(k+2,b-1)});i=b}}
 call(name:string,args:Value[]):Value{const fn=this.f.get(name);if(!fn)return 0;const saveT=this.t,saveP=this.p;const old:Record<string,Value|undefined>={};const had:Record<string,boolean>={};fn.params.forEach((n,i)=>{had[n]=n in this.env;old[n]=this.env[n];this.env[n]=args[i]??0});this.t=[...fn.body,{kind:"eof",value:"eof"}];this.p=0;try{const r=this.block(false);fn.params.forEach(n=>had[n]?this.env[n]=old[n]!:delete this.env[n]);this.t=saveT;this.p=saveP;return r.v??0}catch(e){fn.params.forEach(n=>had[n]?this.env[n]=old[n]!:delete this.env[n]);this.t=saveT;this.p=saveP;throw e}}
 peek(v?:string):any{return v===undefined?this.t[this.p]:this.t[this.p]?.value===v}take(v?:string){const x=this.t[this.p];if(v&&x.value!==v)throw new Error(`Expected ${v}, found ${x.value}`);this.p++;return x}accept(v:string){if(this.peek(v)){this.p++;return true}return false}
 block(braced:boolean){if(braced)this.take("{");let r:any={};while(!this.peek("eof")&&(!braced||!this.peek("}"))){r=this.stmt();if(r.s)return r}if(braced)this.take("}");return r}
 stmt():any{if(this.accept(";"))return{};if(this.peek("if")){this.take("if");this.take("(");const c=this.truth(this.expr());this.take(")");const a=this.p,ae=this.skip(a);let r={};if(c)r=this.execAt(a);this.p=ae;if(this.accept("else")){const b=this.p,be=this.skip(b);if(!c)r=this.execAt(b);this.p=be}return r}if(this.peek("for"))return this.forStmt();if(this.peek("while"))return this.whileStmt();if(this.peek("switch"))return this.switchStmt();if(this.accept("break")){this.take(";");return{s:"break"}}if(this.accept("continue")){this.take(";");return{s:"continue"}}if(this.accept("return")){const v=this.peek(";")?0:this.expr();this.accept(";");return{s:"return",v}}if(this.peek("{"))return this.block(true);if(this.decl())return{};this.expr();this.accept(";");return{}}
 execAt(i:number){const save=this.p;this.p=i;const r=this.stmt();this.p=save;return r}skip(i:number){const save=this.p;this.p=i;if(this.peek("{")){let d=0;do{const x=this.take().value;if(x==="{")d++;if(x=== "}")d--}while(d&&!this.peek("eof"))}else{while(!this.peek(";")&&!this.peek("eof"))this.p++;this.accept(";")}const e=this.p;this.p=save;return e}
 whileStmt(){this.take("while");this.take("(");const c=this.p;let d=1;while(d){const x=this.take().value;if(x==="(")d++;if(x===")")d--}const b=this.p,be=this.skip(b);let g=0;while(this.truth(this.evalAt(c))&&g++<10000&&!this.stopped){const r=this.execAt(b);if(r.s==="break")break;if(r.s==="return")return r;this.p=be}this.p=be;return{}}
 forStmt(){this.take("for");this.take("(");if(!this.peek(";")){if(this.decl(false)){}else this.expr()}this.take(";");const c=this.p;while(!this.peek(";"))this.p++;const ce=this.p;this.take(";");const inc=this.p;while(!this.peek(")"))this.p++;const ie=this.p;this.take(")");const b=this.p,be=this.skip(b);let g=0;while((c===ce||this.truth(this.evalAt(c)))&&g++<10000&&!this.stopped){const r=this.execAt(b);if(r.s==="break")break;if(r.s==="return")return r;this.p=inc;this.expr();this.p=be}this.p=be;return{}}
 switchStmt(){this.take("switch");this.take("(");const v=this.expr();this.take(")");this.take("{");let active=false,matched=false;while(!this.peek("}")&&!this.peek("eof")){if(this.accept("case")){const c=this.expr();this.take(":");active=matched||this.eq(v,c);if(active)matched=true;continue}if(this.accept("default")){this.take(":");active=!matched;matched=true;continue}if(active){const r=this.stmt();if(r.s==="break")break;if(r.s)return r}else this.skipOne()}this.take("}");return{}}
 skipOne(){if(this.peek("{"))this.skip(this.p);else{while(!this.peek(";")&&!this.peek("}")&&!this.peek("eof"))this.p++;this.accept(";")}}
 decl(eatSemi=true){let save=this.p;this.accept("const");if(this.accept("unsigned"))this.accept("long");else if(!["int","long","bool","boolean","byte","float","double","char","String"].includes(this.peek()!.value)){this.p=save;return false}else this.take();if(this.peek()?.kind!=="id"){this.p=save;return false}const n=this.take().value;if(this.accept("[")){const z=Math.max(0,Math.floor(Number(this.expr())));this.take("]");const a:Value[]=Array.from({length:z},()=>0);if(this.accept("=")){this.take("{");let i=0;while(!this.peek("}")&&!this.peek("eof")){if(i<z)a[i]=this.expr();else this.expr();i++;if(!this.accept(","))break}this.take("}")}this.arrays.set(n,a);this.env[n]=a;if(eatSemi)this.accept(";");return true}let v:Value=0;if(this.accept("="))v=this.expr();this.env[n]=v;if(eatSemi)this.accept(";");return true}
 expr(){return this.assign()}assign():Value{const left=this.binary(0);const op=this.peek()?.value;if(["=","+=","-=","*=","/=","%="].includes(op)){this.take();const n=this.lv;const r=this.assign();const a=Number(this.env[n]??0),b=Number(r);this.env[n]=op==="="?r:op==="+="?a+b:op==="-="?a-b:op==="*="?a*b:op==="/="?(b?a/b:0):(b?a%b:0);return this.env[n]}return left}lv="";prec(o:string){return{"||":1,"&&":2,"==":3,"!=":3,"<":4,"<=":4,">":4,">=":4,"+":5,"-":5,"*":6,"/":6,"%":6,"<<":7,">>":7}[o]??-1}binary(m:number){let a=this.unary();while(this.prec(this.peek()?.value)>=m){const o=this.take().value,b=this.binary(this.prec(o)+1);a=this.apply(o,a,b)}return a}unary():Value{if(this.accept("!"))return this.truth(this.unary())?0:1;if(this.accept("-"))return-Number(this.unary());if(this.accept("+"))return Number(this.unary());if(this.accept("++")){const n=this.take().value;this.env[n]=Number(this.env[n]??0)+1;this.lv=n;return this.env[n]}if(this.accept("--")){const n=this.take().value;this.env[n]=Number(this.env[n]??0)-1;this.lv=n;return this.env[n]}let v=this.primary();if(this.peek("++")||this.peek("--")){const o=this.take().value,n=this.lv;if(n){const old=Number(this.env[n]??0);this.env[n]=old+(o==="++"?1:-1);return old}}return v}
 primary():Value{const x=this.take();if(x.kind==="num")return Number(x.value);if(x.kind==="str")return x.value;if(x.value==="("){const v=this.expr();this.take(")");return v}if(x.kind==="id"){if(x.value==="true"||x.value==="HIGH")return 1;if(x.value==="false"||x.value==="LOW")return 0;if(x.value==="INPUT"||x.value==="OUTPUT"||x.value==="INPUT_PULLUP")return x.value;if(this.accept("(")){const a:Value[]=[];while(!this.peek(")")&&!this.peek("eof")){a.push(this.assign());if(!this.accept(","))break}this.take(")");return this.builtin(x.value,a)}if(this.accept("[")){const i=Math.floor(Number(this.expr()));this.take("]");this.lv=x.value;return this.arrays.get(x.value)?.[i]??0}this.lv=x.value;return this.env[x.value]??0}throw new Error(`Unexpected token ${x.value} at ${this.p}`)}
 evalAt(i:number){const s=this.p;this.p=i;const v=this.expr();this.p=s;return v}truth(v:Value){return Array.isArray(v)?v.length>0:typeof v==="string"?v.length>0:Number(v)!==0}eq(a:Value,b:Value){return String(a)===String(b)}scalar(v:Value){return Array.isArray(v)?v[0]??0:v}
 apply(o:string,a:Value,b:Value):Value{const x=this.scalar(a),y=this.scalar(b);switch(o){case"||":return this.truth(x)||this.truth(y)?1:0;case"&&":return this.truth(x)&&this.truth(y)?1:0;case"==":return this.eq(x,y)?1:0;case"!=":return this.eq(x,y)?0:1;case"<":return Number(x)<Number(y)?1:0;case"<=":return Number(x)<=Number(y)?1:0;case">":return Number(x)>Number(y)?1:0;case">=":return Number(x)>=Number(y)?1:0;case"+":return typeof x==="string"||typeof y==="string"?String(x)+String(y):Number(x)+Number(y);case"-":return Number(x)-Number(y);case"*":return Number(x)*Number(y);case"/":return Number(y)?Number(x)/Number(y):0;case"%":return Number(y)?Number(x)%Number(y):0;case"<<":return Number(x)<<Number(y);case">>":return Number(x)>>Number(y);default:return 0}}
 builtin(n:string,a:Value[]):Value{const l=n.toLowerCase();if(l==="millis")return this.runtime.timeMs;if(l==="delay"){this.runtime.timeMs+=Math.max(0,Number(a[0]??0));return 0}if(l==="pinmode"){const p=this.pin(a[0]);this.state.modes[p]=String(a[1]) as PinMode;if(this.state.modes[p]==="INPUT_PULLUP")this.state.digital[p]=1;return 0}if(l==="digitalread"){const p=this.pin(a[0]);if(this.inputs.digital&&p in this.inputs.digital)return this.inputs.digital[p];if((this.state.modes[p]??"INPUT")==="INPUT_PULLUP")return 1;return this.state.digital[p]??0}if(l==="risingedge"||l==="digitalrisingedge"){const p=this.pin(a[0]);const prev=this.runtime.prevStableDigital?.[p];const cur=this.runtime.stableDigital?.[p]??this.inputs.digital?.[p];return prev===0&&cur===1?1:0}if(l==="fallingedge"||l==="digitalfallingedge"){const p=this.pin(a[0]);const prev=this.runtime.prevStableDigital?.[p];const cur=this.runtime.stableDigital?.[p]??this.inputs.digital?.[p];return prev===1&&cur===0?1:0}if(l==="digitalwrite"){const p=this.pin(a[0]),v=this.truth(a[1])?1:0;this.state.digital[p]=v;this.events.push({pin:p,value:v});return 0}if(l==="analogread"){const raw=String(a[0]??"0");const p=/^\d+$/.test(raw)?`a${raw}`:this.pin(a[0]);const key=p.startsWith("a")?p:p;const v=this.inputs.analog?.[key]??this.inputs.analog?.[p]??0;return Math.max(0,Math.min(1023,Math.round(v/5*1023)))}if(l==="analogwrite"){const p=this.pin(a[0]),v=Math.max(0,Math.min(255,Number(a[1]??0)));this.runtime.pwmDuty=this.runtime.pwmDuty||{};this.runtime.pwmDuty[p]=v;this.state.modes[p]="OUTPUT";this.state.digital[p]=(v>=128?1:0) as 0|1;this.events.push({pin:p,value:this.state.digital[p]});return 0}if(["byte","int","long","float","double","char"].includes(l))return Number(a[0]??0);if(l==="min")return Math.min(Number(a[0]),Number(a[1]));if(l==="max")return Math.max(Number(a[0]),Number(a[1]));if(l==="constrain")return Math.max(Number(a[1]),Math.min(Number(a[0]),Number(a[2])));if(l.startsWith("lcd_")){this.lcd(l.slice(4),a);return 0}if(l.startsWith("display_")||l.startsWith("u8g2_"))return 0;return this.call(n,a)}
 pin(v:Value){const s=String(v);return/^\d+$/.test(s)?`d${s}`:s.toLowerCase()}
 lcd(m:string,a:Value[]){
  const text = a[0]===undefined||a[0]===null?"":typeof a[0]==="number"?(Number.isInteger(a[0])?String(a[0]):String(a[0])):typeof a[0]==="boolean"?(a[0]?"1":"0"):String(a[0]);
  if(m==="begin"){
    this.lcdCols=Math.max(1,Math.min(40,Number(a[0]??16)));
    this.lcdRows=Math.max(1,Math.min(4,Number(a[1]??2)));
    this.state.lcdSoftCols=this.lcdCols;this.state.lcdSoftRows=this.lcdRows;
    this.state.lcdSoftLines=Array.from({length:this.lcdRows},()=>" ".repeat(this.lcdCols));
    this.writeNibble(0x03);this.writeNibble(0x03);this.writeNibble(0x03);this.writeNibble(0x02);
    this.writeByte(this.lcdRows>1?0x28:0x20,0);this.writeByte(0x0c,0);this.writeByte(0x01,0);this.writeByte(0x06,0);
    this.lcdCol=0;this.lcdRow=0;return;
  }
  if(m==="clear"){this.writeByte(0x01,0);this.state.lcdSoftLines=Array.from({length:this.lcdRows},()=>" ".repeat(this.lcdCols));this.lcdCol=0;this.lcdRow=0;return}
  if(m==="home"){this.writeByte(0x02,0);this.lcdCol=0;this.lcdRow=0;return}
  if(m==="setcursor"){const col=Math.max(0,Number(a[0]??0)),row=Math.max(0,Number(a[1]??0));const off=row===0?0:row===1?0x40:row===2?0x14:0x54;this.writeByte(0x80+off+col,0);this.lcdCol=col;this.lcdRow=row;return}
  if(m==="createchar"){
    const n=Number(a[0]??0)&7;
    let data:number[]=[];
    if(Array.isArray(a[1])) data=a[1].map(x=>Number(x)&0xff);
    else if(typeof a[1]==="string"&&this.arrays.has(a[1])) data=(this.arrays.get(a[1])??[]).map(x=>Number(x)&0xff);
    this.chars[n]=data.slice(0,8);
    this.writeByte(0x40|(n<<3),0);
    for(let i=0;i<8;i++) this.writeByte(data[i]??0,1);
    return;
  }
  if(m==="print"||m==="println"){let s=text;if(m==="println")s+="\n";this.writeSoft(s);return}
  if(m==="write"){
    const code=Number(a[0]??0)&0xff;
    if(code<=7&&this.chars[code]){this.writeSoft("\uFFFD");this.writeByte(code,1)}
    else this.writeSoft(String.fromCharCode(code));
    return;
  }
  if(m==="display"){this.writeByte(0x0c,0);return}
  if(m==="nodisplay"){this.writeByte(0x08,0);return}
  if(m==="cursor"){this.writeByte(0x0e,0);return}
  if(m==="nocursor"){this.writeByte(0x0c,0);return}
  if(m==="blink"){this.writeByte(0x0d,0);return}
  if(m==="noblink"){this.writeByte(0x0c,0);return}
}
 writeSoft(s:string){if(!this.state.lcdSoftLines)this.state.lcdSoftLines=Array.from({length:this.lcdRows},()=>" ".repeat(this.lcdCols));for(const ch of s){if(ch==="\n"){this.lcdRow=Math.min(this.lcdRows-1,this.lcdRow+1);this.lcdCol=0;continue}if(this.lcdCol>=this.lcdCols){this.lcdRow=Math.min(this.lcdRows-1,this.lcdRow+1);this.lcdCol=0}const line=this.state.lcdSoftLines[this.lcdRow]??" ".repeat(this.lcdCols);this.state.lcdSoftLines[this.lcdRow]=line.slice(0,this.lcdCol)+ch+line.slice(this.lcdCol+1);this.lcdCol++;this.writeByte(ch.charCodeAt(0),1)}}
 writeNibble(n:number){const p=this.state.lcdPins;if(!p)return;this.writePin(p.d4,(n&1) as 0|1);this.writePin(p.d5,((n>>1)&1) as 0|1);this.writePin(p.d6,((n>>2)&1) as 0|1);this.writePin(p.d7,((n>>3)&1) as 0|1);this.writePin(p.e,1);this.writePin(p.e,0)}
 writePin(pin:string,v:0|1){this.state.digital[pin]=v;this.events.push({pin,value:v})}
 writeByte(v:number,rs:0|1){const p=this.state.lcdPins;if(!p)return;this.writePin(p.rs,rs);this.writeNib(p,((v>>4)&15));this.writeNib(p,v&15)}
 writeNib(p:NonNullable<McuRuntimeState["lcdPins"]>,n:number){this.writePin(p.d4,(n&1) as 0|1);this.writePin(p.d5,((n>>1)&1) as 0|1);this.writePin(p.d6,((n>>2)&1) as 0|1);this.writePin(p.d7,((n>>3)&1) as 0|1);this.writePin(p.e,1);this.writePin(p.e,0)}
}

export function runArduinoSketch(source:string,state:McuRuntimeState,runtime:PersistentMcuRuntime,inputs:McuRuntimeInputs,events:McuPinEvent[]){new Interpreter(source,state,runtime,inputs,events).run()}
